### ISSUE TITLE
not working when exporter is running is a different cluster and scraping via https

### ISSUE THREAD

**Issue by isshwar** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#37]
Hi,

I am trying to run the exporter on a k8s cluster behind a load balancer. My prom is set up in another vm and now when i try to get the metrics from flashblade, it is always returning 400 bad request. When i run the same exporter on prom vm and let the prometheus vm communicate via internal ip, able to scrape the metrics. 
not sure what is going wrong when scraping on a different kubernetes cluster. my prom config is 

- job_name: 'purestorage-fb'
   scheme: https
   metrics_path: /metrics/array
   bearer_token: <redacted>
   params:
     endpoint: ['pt-flashblade-001.com]
    static_configs:
      - targets: ["pure-exporter.com"]
         labels:
          location: germany
          site: frankfurt
          instance: pt-flashblade-001

whereas just changing the endpoint to the local container is working

- job_name: 'purestorage-fb'
   scheme: https
   metrics_path: /metrics/array
   bearer_token: <redacted>
   params:
     endpoint: ['pt-flashblade-001.com]
    static_configs:
      - targets: ["pure-fb-exporter:9491"]
         labels:
          location: germany
          site: frankfurt
          instance: pt-flashblade-001

Thanks for any help

**Comment by james-laing** [comment]
Hi @isshwar - apologies for the late response. You might even be up and running now.

In the `static_configs` section the target port was missing. I have re-written it here if it helps.

Let me know if you get it working.

```
# pt-flashblade-001
  - job_name: 'purefb_array_arrayname01'
    metrics_path: /metrics/array
    # Bearer authorization token
    authorization:
      credentials: ####
    params:
      endpoint: ['pt-flashblade-001.com']

    static_configs:
    # purefb openmetrics exporter
    - targets:
      - pure-fb-exporter:9491
      labels:
        location: Germany
        site: Frankfurt
        instance: pt-flashblade-001
        env: production
```
